name: reem_s_application9
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.4.4 <4.0.0'
  
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  connectivity_plus: ^6.0.4
  flutter_rating_bar: ^4.0.1
  flutter_switch: ^0.3.2
  google_fonts: ^6.2.1
  pin_code_fields: ^8.0.1
  flutter_chat_ui: ^1.6.15
<<<<<<< Updated upstream
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  path_provider: ^2.0.10
  vector_graphics: ^1.1.18
  vector_graphics_codec: ^1.1.13
  vector_graphics_compiler: ^1.1.16


=======

  #مكتبات فايربيس 
  firebase_core: ^2.1.1
  
>>>>>>> Stashed changes
dev_dependencies: 
  flutter_test:
      sdk: flutter




flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
